pipeline:
  name: crash test
  identifier: crash_test
  projectIdentifier: Mower
  orgIdentifier: stf
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: stfgit/mower-java
        build: <+input>
  stages:
    - stage:
        name: sources scan
        identifier: sources_scan
        template:
          templateRef: account.source_code_scan
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: SecurityTests
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.k8sdocacloud
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - parallel:
                      - step:
                          identifier: owasp
                          type: Owasp
                          spec:
                            advanced:
                              fail_on_severity: none
                            resources:
                              limits:
                                memory: <+input>.default(2Gi)
                                cpu: <+input>.default(500m)
                      - step:
                          identifier: aquatrivy
                          type: AquaTrivy
                          spec:
                            advanced:
                              fail_on_severity: none
                            resources:
                              limits:
                                memory: <+input>
                                cpu: <+input>
                      - step:
                          identifier: gitleaks
                          type: Gitleaks
                          spec:
                            advanced:
                              fail_on_severity: low
                            resources:
                              limits:
                                memory: <+input>
                                cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: build and publish
        identifier: build_and_publish
        template:
          templateRef: account.maven_build_stage_tplt
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.k8sdocacloud
                  namespace: harness-ci
              execution:
                steps:
                  - step:
                      identifier: mvn_build
                      type: Run
                      spec:
                        connectorRef: org.Dockerhub
                        image: <+input>.default(maven:3.9.6-eclipse-temurin-21)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: mvn_test_with_coverage
                      type: Run
                      spec:
                        connectorRef: org.Dockerhub
                        image: <+input>.default(maven:3.9.6-eclipse-temurin-21)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: coverage_quality_gate
                      type: Run
                      spec:
                        connectorRef: org.Dockerhub
                        image: <+input>.default(alpine:latest)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: build_and_push_docker_image
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: org.Dockerhub
                        repo: stfgit/mower-java
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: images scan
        identifier: images_scan
        template:
          templateRef: account.images_scan
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: SecurityTests
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: account.k8sdocacloud
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - step:
                      identifier: aquatrivy_container
                      type: AquaTrivy
                      spec:
                        advanced:
                          fail_on_severity: none
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: dev deployment
        identifier: dev_deployment
        tags: {}
        template:
          templateRef: account.deploy_k8s
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: development
                gitBranch: main
                infrastructureDefinitions:
                  - identifier: infra_dev
              service:
                serviceRef: mower_svc
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: javaImage
                gitBranch: main
            delegateSelectors:
              - helm-delegate
