pipeline:
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: <+input>
        build: <+input>
  stages:
    - stage:
        name: scan sources
        identifier: source_code_scan
        template:
          templateRef: account.source_code_scan
          versionLabel: v0.1
          templateInputs:
            type: SecurityTests
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - parallel:
                      - step:
                          identifier: owasp
                          type: Owasp
                          spec:
                            advanced:
                              fail_on_severity: <+input>
                            resources:
                              limits:
                                memory: <+input>.default(2Gi)
                                cpu: <+input>.default(500m)
                      - step:
                          identifier: aquatrivy
                          type: AquaTrivy
                          spec:
                            advanced:
                              fail_on_severity: <+input>
                            resources:
                              limits:
                                memory: <+input>
                                cpu: <+input>
                      - step:
                          identifier: gitleaks
                          type: Gitleaks
                          spec:
                            advanced:
                              fail_on_severity: <+input>
                            resources:
                              limits:
                                memory: <+input>
                                cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: mvn build and push
        identifier: mvn_build_and_push
        template:
          templateRef: account.maven_build_stage_tplt
          versionLabel: v0.1
          templateInputs:
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - step:
                      identifier: mvn_build
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(maven:3.9.6-eclipse-temurin-21)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: mvn_test_with_coverage
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(maven:3.9.6-eclipse-temurin-21)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: coverage_quality_gate
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(alpine:latest)
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: build_and_push_docker_image
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
                        repo: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: npm build and push
        identifier: npm_build_and_push
        template:
          templateRef: account.npm_build
          versionLabel: v0.1
          gitBranch: main
          templateInputs:
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - step:
                      identifier: Install_Dependencies
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                        command: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: ESLint_Check
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                        command: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: Build_Application
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                        command: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: Unit_Tests
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                        command: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: NPM_Audit
                      type: Run
                      spec:
                        connectorRef: <+input>
                        image: <+input>.default(node:20)
                        command: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
                  - step:
                      identifier: BuildAndPushDockerRegistry_1
                      type: BuildAndPushDockerRegistry
                      spec:
                        connectorRef: <+input>
                        repo: <+input>
                        tags: <+input>
                        dockerfile: <+input>
                        context: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
    - stage:
        name: scan images
        identifier: scan_images
        template:
          templateRef: account.images_scan
          versionLabel: v0.1
          templateInputs:
            type: SecurityTests
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>.default(harness-ci)
              execution:
                steps:
                  - step:
                      identifier: aquatrivy_container
                      type: AquaTrivy
                      spec:
                        advanced:
                          fail_on_severity: <+input>
                        resources:
                          limits:
                            memory: <+input>
                            cpu: <+input>
            delegateSelectors: <+input>
    - stage:
        name: deploy dev
        identifier: deploy_dev
        template:
          templateRef: account.deploy_k8s
          versionLabel: v0.1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: development
                infrastructureDefinitions:
                  - identifier: infra_dev
              service:
                serviceRef: mower_fullstack_service
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
                gitBranch: main
            delegateSelectors:
              - helm-delegate
    - stage:
        name: mep approval
        identifier: mep_approval
        template:
          templateRef: account.manual_approval
          versionLabel: v0.1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: approval
                      type: HarnessApproval
                      spec:
                        approvers:
                          minimumCount: <+input>.default(1)
                          userGroups: <+input>
            delegateSelectors: <+input>
    - stage:
        name: deploy prod
        identifier: deploy_prod
        template:
          templateRef: account.deploy_k8s
          versionLabel: v0.1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: prod
                infrastructureDefinitions:
                  - identifier: mower_infra
              service:
                useFromStage:
                  stage: deploy_dev
            delegateSelectors:
              - helm-delegate
  name: mower-java - fullstack templates
  identifier: mowerjava_fullstack_templates
  tags:
    fullstack: ""
    backend: ""
    frontend: ""
    templates: ""
  projectIdentifier: Mower
  orgIdentifier: stf
