pipeline:
  identifier: Build_stfgit_mower_java_1749822312194
  name: Build mower-java
  orgIdentifier: stf
  projectIdentifier: Mower
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: stfgit/mower-java
  stages:
    - stage:
        name: Build and test
        identifier: Build_and_test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.kubdesktop
              namespace: mower
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Test
                  identifier: Test
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.6-eclipse-temurin-21
                    shell: Sh
                    command: |-
                      mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
                      mvn test -B
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
