apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backend.app.name }}
    environment: {{ .Values.environment }}
    tier: backend
spec:
  selector:
    app: {{ .Values.backend.app.name }}
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: {{ .Values.backend.service.type }}