apiVersion: v1
kind: ConfigMap
metadata:
  name: mower-input-data
  namespace: mower
  labels:
    app: mower-java
data:
  # Fichier d'instructions pour le mower
  instructions.txt: |
    5 5
    1 2 N
    GAGAGAGAA
    3 3 E
    AADAADADDA
  
  # Configuration applicative
  application.properties: |
    output.format=json
    verbose=true
    validate.input=true