apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.frontend.app.name }}
    environment: {{ .Values.environment }}
    tier: frontend
spec:
  selector:
    app: {{ .Values.frontend.app.name }}
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: {{ .Values.frontend.service.type }}