environment:
  name: dev
  identifier: dev
  orgIdentifier: stf
  description: ""
  tags: {}
  type: PreProduction
  yaml: |
    environment:
      name: "dev "
      identifier: dev
      orgIdentifier: stf
      type: PreProduction
      description: ""
      tags: {}
